In [3]:
# Import required libraries
import os
import pandas as pd
from pathlib import Path
import hvplot.pandas
import pandas as pd
pd.options.mode.chained_assignment = None  # default='warn'

In [4]:
# Import required Data,including Increase and Decrease
date = '09-13-2022'
increase = pd.read_csv(os.path.join(Path.cwd(),f'../Data/Increase/stocks-increase-change-in-open-interest-{date}.csv'))
decrease = pd.read_csv(os.path.join(Path.cwd(),f'../Data/Decrease/stocks-decrease-change-in-open-interest-{date}.csv'))

#show dataframe

display(increase.head())
display(decrease.head())

,Symbol,Price,Type,Strike,Exp Date,DTE,Bid,Midpoint,Ask,Last,Volume,Open Int,OI Chg,IV,Time
0,LAZR,8.82,Call,10.0,2022-09-23,10.0,0.15,0.16,0.17,0.16,1371.0,42892.0,"+42,439",90.75%,2022-09-13
1,VALE,13.15,Call,14.0,2022-10-21,38.0,0.45,0.49,0.53,0.50,619.0,32489.0,"+29,625",50.12%,2022-09-13
2,CLVS,1.49,Call,1.5,2022-09-16,3.0,0.03,0.07,0.11,0.11,7653.0,27255.0,"+25,323",212.66%,2022-09-13
3,CHPT,17.54,Call,18.5,2022-09-16,3.0,0.21,0.23,0.25,0.24,3902.0,28622.0,"+23,906",92.28%,2022-09-13
4,IGT,17.95,Call,21.0,2022-10-21,38.0,0.31,0.36,0.40,0.37,891.0,20875.0,"+20,735",56.23%,2022-09-13

,Symbol,Price,Type,Strike,Exp Date,DTE,Bid,Midpoint,Ask,Last,Volume,Open Int,OI Chg,IV,Time
0,MMM,120.47,Put,200.0,2022-09-16,3.0,79.25,79.53,79.80,79.00,5049.0,37530.0,"-31,298",269.57%,2022-09-13
1,CHPT,17.54,Call,16.0,2022-09-16,3.0,1.60,1.66,1.72,1.62,1101.0,17470.0,"-17,186",86.27%,2022-09-13
2,BAC,34.00,Call,35.0,2022-09-16,3.0,0.13,0.15,0.16,0.13,10386.0,29610.0,"-15,511",37.70%,2022-09-13
3,AMZN,126.82,Call,120.0,2022-09-16,3.0,7.00,7.65,8.30,7.50,1139.0,85036.0,"-12,475",64.33%,2022-09-13
4,AMZN,126.82,Put,120.0,2022-09-16,3.0,0.45,0.46,0.47,0.45,13362.0,94322.0,"-11,035",56.56%,2022-09-13

In [5]:
# check Missing Data

display(increase.isnull().sum())
display(increase.isnull().sum())

Symbol      0
Price       1
Type        1
Strike      1
Exp Date    1
DTE         1
Bid         1
Midpoint    1
Ask         1
Last        1
Volume      1
Open Int    1
OI Chg      1
IV          1
Time        1
dtype: int64

Symbol      0
Price       1
Type        1
Strike      1
Exp Date    1
DTE         1
Bid         1
Midpoint    1
Ask         1
Last        1
Volume      1
Open Int    1
OI Chg      1
IV          1
Time        1
dtype: int64

In [6]:
# Handle Missing Data

increase = increase.dropna()
decrease = decrease.dropna()

In [7]:
#Select the data only equal to minimun DTE (closest to expired).
increase_min_DTE = increase[increase['DTE'] == increase['DTE'].min()]
decrease_min_DTE = decrease[decrease['DTE'] == decrease['DTE'].min()]

# show dataframe
display(increase_min_DTE)
display(decrease_min_DTE)

,Symbol,Price,Type,Strike,Exp Date,DTE,Bid,Midpoint,Ask,Last,Volume,Open Int,OI Chg,IV,Time
2,CLVS,1.49,Call,1.5,2022-09-16,3.0,0.03,0.07,0.11,0.11,7653.0,27255.0,"+25,323",212.66%,2022-09-13
3,CHPT,17.54,Call,18.5,2022-09-16,3.0,0.21,0.23,0.25,0.24,3902.0,28622.0,"+23,906",92.28%,2022-09-13
6,AAPL,153.84,Put,160.0,2022-09-16,3.0,6.25,6.40,6.55,6.50,46433.0,54498.0,"+18,531",38.44%,2022-09-13
8,NIO,21.97,Put,20.0,2022-09-16,3.0,0.13,0.14,0.14,0.14,17771.0,25108.0,"+13,073",98.39%,2022-09-13
10,NIO,21.97,Put,20.5,2022-09-16,3.0,0.20,0.21,0.21,0.21,11226.0,12786.0,"+12,104",93.69%,2022-09-13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
984,AMZN,126.82,Put,131.0,2022-09-16,3.0,4.70,4.85,5.00,4.97,4040.0,6684.0,+382,49.80%,2022-09-13
985,NVDA,131.31,Call,145.0,2022-09-16,3.0,0.16,0.17,0.18,0.16,8550.0,7990.0,+381,65.31%,2022-09-13
995,AVYA,1.82,Call,1.5,2022-09-16,3.0,0.30,0.35,0.40,0.37,1403.0,6644.0,+378,271.20%,2022-09-13
997,RBLX,43.87,Put,43.0,2022-09-16,3.0,1.32,1.36,1.40,1.33,883.0,660.0,+377,110.41%,2022-09-13
999,SQ,69.58,Put,74.0,2022-09-16,3.0,4.80,4.95,5.10,5.00,535.0,915.0,+374,80.91%,2022-09-13

,Symbol,Price,Type,Strike,Exp Date,DTE,Bid,Midpoint,Ask,Last,Volume,Open Int,OI Chg,IV,Time
0,MMM,120.47,Put,200.0,2022-09-16,3.0,79.25,79.53,79.80,79.00,5049.0,37530.0,"-31,298",269.57%,2022-09-13
1,CHPT,17.54,Call,16.0,2022-09-16,3.0,1.60,1.66,1.72,1.62,1101.0,17470.0,"-17,186",86.27%,2022-09-13
2,BAC,34.00,Call,35.0,2022-09-16,3.0,0.13,0.15,0.16,0.13,10386.0,29610.0,"-15,511",37.70%,2022-09-13
3,AMZN,126.82,Call,120.0,2022-09-16,3.0,7.00,7.65,8.30,7.50,1139.0,85036.0,"-12,475",64.33%,2022-09-13
4,AMZN,126.82,Put,120.0,2022-09-16,3.0,0.45,0.46,0.47,0.45,13362.0,94322.0,"-11,035",56.56%,2022-09-13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
989,VST,24.98,Put,25.0,2022-09-16,3.0,0.30,0.35,0.40,0.35,1510.0,309.0,-16,37.57%,2022-09-13
991,MTCH,59.79,Call,62.0,2022-09-16,3.0,0.50,0.56,0.62,0.56,1537.0,677.0,-16,63.21%,2022-09-13
992,GOOG,105.31,Call,108.0,2022-09-16,3.0,0.55,0.60,0.65,0.60,2767.0,1232.0,-16,41.25%,2022-09-13
993,WMT,135.22,Put,134.0,2022-09-16,3.0,0.83,0.86,0.88,0.79,968.0,1656.0,-15,28.41%,2022-09-13
997,SQ,69.58,Put,60.0,2022-09-16,3.0,0.10,0.12,0.13,0.12,502.0,5422.0,-15,99.18%,2022-09-13

In [8]:
#Merge data of increase and decrease dataframe

combine_df = increase_min_DTE.merge(decrease_min_DTE, how= 'outer')

In [9]:
# Sort by this orders Symbol,Type,Strike,Open Int,Volume,OI Chg,IV

combine_sort_df = combine_df.sort_values(['Symbol','Type','Strike','Open Int','Volume','OI Chg','IV'])

In [13]:
# Create the function for clean data acquire.
def get_data(date):

        increase = pd.read_csv(os.path.join(Path.cwd(),f'../Data/Increase/stocks-increase-change-in-open-interest-{date}.csv'))
        decrease = pd.read_csv(os.path.join(Path.cwd(),f'../Data/Decrease/stocks-decrease-change-in-open-interest-{date}.csv'))
        combine_df = increase.merge(decrease, how= 'outer')
        combine_min_DTE = combine_df[combine_df['DTE'] == combine_df['DTE'].min()]
        combine_min_DTE = combine_min_DTE.dropna()
        combine_sort_df = combine_min_DTE.sort_values(['Symbol','Type','Strike','Open Int','Volume','OI Chg','IV'])
        
        return combine_sort_df

In [14]:
a = get_data('09-13-2022')

a.head()

,Symbol,Price,Type,Strike,Exp Date,DTE,Bid,Midpoint,Ask,Last,Volume,Open Int,OI Chg,IV,Time
1448,AAL,13.68,Call,13.5,2022-09-16,3.0,0.41,0.42,0.43,0.42,983.0,3713.0,-124,65.22%,2022-09-13
1058,AAL,13.68,Call,14.0,2022-09-16,3.0,0.17,0.18,0.19,0.19,4682.0,19976.0,"-1,406",64.80%,2022-09-13
1631,AAL,13.68,Put,13.0,2022-09-16,3.0,0.09,0.10,0.10,0.10,3197.0,40030.0,-61,69.83%,2022-09-13
332,AAL,13.68,Put,13.5,2022-09-16,3.0,0.21,0.22,0.23,0.23,3529.0,3365.0,"+1,213",63.64%,2022-09-13
303,AAL,13.68,Put,14.0,2022-09-16,3.0,0.47,0.49,0.50,0.47,9410.0,14360.0,"+1,308",56.60%,2022-09-13